# Configuration for no-RAG experiment on aging_dam dataset
# Used for comparing with legacy/qa_norag.py

dataset: aging_dam
model: gpt-4o
retrieval_method: none
k: 0  # Not used for no-RAG, but required by main.py

# Evaluation settings
eval_metrics:
  - exact_match
  - f1
  - rouge
  - bleu
  - semantic

# Output settings
output_dir: output_new
save: true
max_samples: 5  # Limit to 5 samples for testing
verbose: true

# LLM settings
temperature: 0.0
max_tokens: 1024
seed: 42  # For reproducibility